### ISSUE TITLE
Feed support

### ISSUE THREAD

**Issue by docop** [lovyan03/ESP32_ScreenShotReceiver#1]
Hi Just see your project and it's very very great looking. Congrats !  As on the lcd support, was all the st7789 lcd that was working with the eSpi lib are just gonna work and faster with your system ?  Also, can we pick or foward an ip stream, like from an ip camera ?
thanks

**Comment by lovyan03** [comment]
Thank you !
My [LovyanGFX](https://github.com/lovyan03/LovyanGFX) is faster than TFT_eSPI.

A comparison video can be found here.
https://twitter.com/lovyan03/status/1276701433308385280

The goal of this project is to find the limits of the frame rate.
That's why I've skipped the extra protocol processing, such as streams, and focused on transferring purely JPEG data only.
